### ISSUE TITLE
Convert profile zaps to BOLT 11 invoices

### ISSUE THREAD

**Issue by moneyball** [damus-io/damus#1067]
Zapping a post results in Damus making the LNURL request to fetch a BOLT 11 invoice which is shared with the corresponding bitcoin wallet. However, profile zaps do not and send the LNURL directly to the bitcoin wallet. This results in wallets such as Cash App and Muun not able to pay a profile zap. Is there any reason a profile zap cannot do the same as a post zap?

**Comment by alltheseas** [comment]
@moneyball I am curious as to why you would zap a profile relative to zapping a note?

What do you think of profile "⚡️" icon to default as non-zap LN payment?

**Comment by alltheseas** [comment]
⚡️ profile tap + muun:
![image](https://user-images.githubusercontent.com/64376233/235987927-08cdecdd-3e72-41e4-91b2-d0d25b12772a.jpeg)

⚡️ profile tap + cash app: 
Cash app does not open/crashes

**Comment by moneyball** [comment]
Yes what you report about Muun and Cash App is consistent with my experience. It is the reason I opened this issue, as I think fixing it is straightforward, and it would improve the experience for all Muun and Cash App users (and possibly more wallets too that do not support LNURL).

**Comment by moneyball** [comment]
> @moneyball I am curious as to why you would zap a profile relative to zapping a note?

It is a feature in the existing Damus product. I'm merely a user not a contributor to Damus.

> What do you think of profile "⚡️" icon to default as non-zap LN payment?

How does a non-zap LN payment differ from a zap LN payment?

**Comment by alltheseas** [comment]
> It is a feature in the existing Damus product. I'm merely a user not a contributor to Damus.

Yes, understood. I was testing if there is a specific job-to-be-done for you using the ⚡️ icon in profile. 

This feature pre-dates "zaps" functionality, and my understanding is team has not examined it since rolling out zaps. 

If you're simply testing out features, and reporting bug thank you. Examining this. 


> How does a non-zap LN payment differ from a zap LN payment?

A "zap" sends some additional information on nostr in addition to the LN payment - e.g. receiver, sender, comment, amount. 

A "non-zap" is simply a LN payment. Afaik nothing is shared on nostr. 

You can hold the "zap" icon on individual notes, where you will have a few options from "zap" to "non-zap". Options closer to "non-zap" share a decreasing amount of information.

**Comment by moneyball** [comment]
My 2 cents product-wise is that profile-level bitcoin payments feel like "paying the person" or "tipping/donating to the person/entity" use case. Whereas bitcoin payments at the post-level feels like supporting the message of the tweet as opposed to the author of the tweet.
