### ISSUE TITLE
Add way to paste nostr wallet connection uri

### ISSUE THREAD

**Issue by benthecarman** [damus-io/damus#1228]
I am trying to setup nwc from another app on my phone but the only way is to scan a Qr, so I need to text the uri to another device and create a qr code.

**Comment by alltheseas** [comment]
For testing purposes which is the other app?

**Comment by benthecarman** [comment]
> For testing purposes which is the other app? 

Mutiny

**Comment by alltheseas** [comment]
## user story
As a Damus user who wants to set up one tap zap with another app on my
Phone, I would like to be able to paste a NWC setup string in Damus, so that I can easily connect Damus with my NWC compatible wallet on my phone. 

### acceptance criteria 
1. Damus wallet menu has a paste NWC setup string option

**Comment by alltheseas** [comment]
https://github.com/damus-io/damus/pull/1235
