### ISSUE TITLE
Apostrophe (or other punctuation) after at tag 250k Sats Bounty

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1375]
_what happens_
When I at tag someone in a post, and I add an apostrophe (without space), the mention (purple text is broken).

![image](https://github.com/damus-io/damus/assets/64376233/d99714a8-9e89-476c-90ab-1cd2dd90aac0)

https://damus.io/note19kndzcdtxuyf0pk4uuj8xqxrd24uq26t5zhmndufc8l9p884tqyq4rmk50

**Comment by shawnyeager** [comment]
I'd argue that this an irritating bug, not an enhancement. I routinely use other clients because I'm unable to use simple punctuation in Damus. I'll commit 250k sats for a fix.

**Comment by danieldaquino** [comment]
I will take a look at this today, and report back with my findings (or a fix, if I can) 👍

**Comment by punterwantsawhalepass** [comment]
🤞

**Comment by geeknik** [comment]
Please review my patch for bounty worthiness. :)

**Comment by alltheseas** [comment]
Thanks @geeknik - Will reviews PRs.

Have you read https://github.com/damus-io/damus/blob/master/docs/CONTRIBUTING.md ?

**Comment by geeknik** [comment]
I have not but I probably should have, so I will. ;) I'm just used to submitting patches on GH.

**Comment by danieldaquino** [comment]
I noticed @geeknik's patch is addressing a section of code that is different from the one I was working on. Since my investigation does not seem to have overlap with his patch, I decided to continue the investigation that I had started yesterday, as it could still add some value.

# Issue reproduction

**iOS:** 16.4 (iPhone 14 Pro simulator)
**Damus:** 1.6 (13) `9fb1cc5b`
**Steps:**

1. Start composing a new note
2. In the editor, tag another user
3. Backspace to get the text cursor right at the edge of the mention link
4. Start typing something
5. Post

**Expected behaviour:** New text should be placed outside the purple link
**Actual behaviour:** New text is added as part of the purple link, and new text disappears when note is posted. 

**Video:** It might be easier to see the issue on a video, so I recorded this video to demonstrate: [https://drive.google.com/file/d/1aWVjucKZPcl319WFFfBTJCAkZEFfazk6/view?usp=sharing](https://drive.google.com/file/d/1aWVjucKZPcl319WFFfBTJCAkZEFfazk6/view?usp=sharing)

I believe this was what @shawnyeager was describing.

# Root cause and fix

The editor uses `NSMutableAttributedString` to represent the mention links. When the text cursor at the very right edge of the text, `UITextInput` interprets it as "inside the link", so new characters get added inside of the link.

When the note gets posted, the parser that creates the note object itself probably ignores any text inside that link, because mention links should contain nothing except the user name anyways.

So, to fix the issue, I needed to customize the editor functionality to avoid having the user modifying the text inside the attributed text with links. I implemented a method from the `UITextViewDelegate` protocol that checks each text edit ([This one](https://developer.apple.com/documentation/uikit/uitextviewdelegate/1618630-textview), and manually handles editing in those special scenarios _(And keeps the default behaviour in other cases)_

# Testing

**iOS:** 16.4 (iPhone 14 Pro simulator)
**Damus:** `ddc8a3e71817c49cfea9befb56d61af25cd47920`
**Steps:**

1. Start composing a new note
2. In the editor, tag another user
3. Backspace to get the text cursor right at the edge of the mention link
4. Start typing something
5. Do several other edge case tests. I believe it's easier to see in video, so I recorded one: [https://drive.google.com/file/d/1IGY99YXdK9SXYKeWXLZVt7sUBvt-nSO3/view?usp=sharing](https://drive.google.com/file/d/1IGY99YXdK9SXYKeWXLZVt7sUBvt-nSO3/view?usp=sharing)
6. Post a note with multiple tags and punctuations right after them.

I also created unit tests to cover several edge cases and prevent future regressions. This and all other unit tests were passing on my end.


# Patch

I have submitted my patch via email, and can be found here: [https://groups.google.com/a/damus.io/g/patches/c/rT4KQmMICWc](https://groups.google.com/a/damus.io/g/patches/c/rT4KQmMICWc)

@jb55, @alltheseas, please let me know if you have any questions, or if you would like further testing. Thank you!

**Comment by alltheseas** [comment]
> I noticed @geeknik's patch is addressing a section of code that is different from the one I was working on. Since my investigation does not seem to have overlap with his patch, I decided to continue the investigation that I had started yesterday, as it could still add some value.
> 
> # Issue reproduction
> **iOS:** 16.4 (iPhone 14 Pro simulator) **Damus:** 1.6 (13) `9fb1cc5b` **Steps:**
> 
> 1. Start composing a new note
> 2. In the editor, tag another user
> 3. Backspace to get the text cursor right at the edge of the mention link
> 4. Start typing something
> 5. Post
> 
> **Expected behaviour:** New text should be placed outside the purple link **Actual behaviour:** New text is added as part of the purple link, and new text disappears when note is posted.
> 
> **Video:** It might be easier to see the issue on a video, so I recorded this video to demonstrate: https://drive.google.com/file/d/1aWVjucKZPcl319WFFfBTJCAkZEFfazk6/view?usp=sharing
> 
> I believe this was what @shawnyeager was describing.
> 
> # Root cause and fix
> The editor uses `NSMutableAttributedString` to represent the mention links. When the text cursor at the very right edge of the text, `UITextInput` interprets it as "inside the link", so new characters get added inside of the link.
> 
> When the note gets posted, the parser that creates the note object itself probably ignores any text inside that link, because mention links should contain nothing except the user name anyways.
> 
> So, to fix the issue, I needed to customize the editor functionality to avoid having the user modifying the text inside the attributed text with links. I implemented a method from the `UITextViewDelegate` protocol that checks each text edit ([This one](https://developer.apple.com/documentation/uikit/uitextviewdelegate/1618630-textview), and manually handles editing in those special scenarios _(And keeps the default behaviour in other cases)_
> 
> # Testing
> **iOS:** 16.4 (iPhone 14 Pro simulator) **Damus:** `ddc8a3e71817c49cfea9befb56d61af25cd47920` **Steps:**
> 
> 1. Start composing a new note
> 2. In the editor, tag another user
> 3. Backspace to get the text cursor right at the edge of the mention link
> 4. Start typing something
> 5. Do several other edge case tests. I believe it's easier to see in video, so I recorded one: https://drive.google.com/file/d/1IGY99YXdK9SXYKeWXLZVt7sUBvt-nSO3/view?usp=sharing
> 6. Post a note with multiple tags and punctuations right after them.
> 
> I also created unit tests to cover several edge cases and prevent future regressions. This and all other unit tests were passing on my end.
> 
> # Patch
> I have submitted my patch via email, and can be found here: https://groups.google.com/a/damus.io/g/patches/c/rT4KQmMICWc
> 
> @jb55, @alltheseas, please let me know if you have any questions, or if you would like further testing. Thank you!

Thank you ser, Will will review.

Is your solution also related to, or perhaps fix https://github.com/damus-io/damus/issues/1156 ?

**Comment by danieldaquino** [comment]
> Is your solution also related to, or perhaps fix https://github.com/damus-io/damus/issues/1156 ?

@alltheseas, I believe they are very likely related, and my patch seems to resolve it from quickly trying to replay the actions in that video.

(One thing to note is that when I worked in the past with special `UITextInput` views such as this one,  I remember that it is an area of coding that inevitably brings many edge cases, so please let me know if you can think of other edge cases I haven't tested yet.)

**Comment by alltheseas** [comment]
> > Is your solution also related to, or perhaps fix #1156 ?
> 
> @alltheseas, I believe they are very likely related, and my patch seems to resolve it from quickly trying to replay the actions in that video.
> 
> (One thing to note is that when I worked in the past with special `UITextInput` views such as this one, I remember that it is an area of coding that inevitably brings many edge cases, so please let me know if you can think of other edge cases I haven't tested yet.)

@danieldaquino this is the only somewhat related one I could find - it involves not having a space before the at symbol: https://github.com/damus-io/damus/issues/1035

**Comment by danieldaquino** [comment]
@alltheseas, I took a look at #1035, but it seems to be a bit different, I believe the issue there is with parsing existing notes to the UI, whereas the issue in this ticket is mostly with the text editor behaviour.

This is just a guess at the moment, but I believe @geeknik's patch could be related to #1035.

**Comment by shawnyeager** [comment]
Excellent. @danieldaquino, feel free to DM me on nostr with your preferred method to receive the 250k sat bounty.

npub1clk6vc9xhjp8q5cws262wuf2eh4zuvwupft03hy4ttqqnm7e0jrq3upup9 or shawn@shawnyeager.com

**Comment by danieldaquino** [comment]
Thank you very much @shawnyeager, I will DM you on Nostr. For identity verification purposes, my npub is `npub13v47pg9dxjq96an8jfev9znhm0k7ntwtlh9y335paj9kyjsjpznqzzl3l8`

**Comment by shawnyeager** [comment]
That makes a lot more sense. Never reply before ☕️. Sats inbound.

**Comment by danieldaquino** [comment]
I confirm the receipt of the bounty. Thank you, @shawnyeager!
