### ISSUE TITLE
when onboarding, create follow hashtag page for new users

### ISSUE THREAD

**Issue by punterwantsawhalepass** [damus-io/damus#1416]

**Comment by alltheseas** [comment]
## user story
As a new user who is creating a new profile and onboarding to Damus, I would like the opportunity to follow one or more hashtag(s) suggested to me by Damus, so that I can have interesting content to browse when I start using Damus.

### acceptance criteria
1. In the onboarding flow, Damus suggests a list of hashtags to follow for the user
2. The user onboarding to Damus can follow none, one, many, or all of the suggested hashtags

### implementation
To start, it is proposed to use a dynamic list provided by Damus team, similar to npub follow suggestions. See related https://github.com/damus-io/damus/issues/1272.

**Comment by alltheseas** [comment]
Just remembered I previously wrote this issue up 🤦‍♂️ . This is a duplicate. Closing. See https://github.com/damus-io/damus/issues/987

**Comment by alltheseas** [comment]
duplicate
