### ISSUE TITLE
Navigation crashes and deadlocks

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#1449]
Seems to happen during nav but I've seen it in other places like the post sheet.

I say deadlock because if you pause in the debugger when it happens it's not at 100% cpu or infinite loop, all threads are sleeping.

**Comment by jb55** [comment]
This seems to be the same issue on 16 and 17 but in different forms.

The crash logs from 16 show random crashes when swiftui accesses NavigationCoordinator's path. 

My guess is some kind of race condition. I tried to put synchronization around the path variable with no luck, but maybe I was doing something wrong.

Will keep at it.

**Comment by danieldaquino** [comment]
I will take a quick stab at reproducing this, just to see if I can familiarize myself with it

**Comment by danieldaquino** [comment]
I did a quick test, but unfortunately I could not repro this issue yet. Here is what I tried:

**iOS:** iOS 17.0 (iPhone 14 Pro) (Unable to test on a physical device at the moment)
**Damus:** 1.6 (17) `40459e247ec5c9890629b87eb60960cf4db98a10`
**Rough steps:**
1. Start following a ton of people
2. Scroll fast down the home view
3. Click on random links (hashtags, profiles, comments, etc) to get to a very deep level of navigation (At least 10 levels deep)
4. Simulate memory warning and continue randomly navigating
5. Quickly tap "back" buttons to go back to the root view
6. Scroll down the hove timeline fast and simulate memory warnings
7. Go to various profiles and request follower counts while continuing to navigate.

**Results:** No crashes on my end

Maybe this is something that would happen only a physical device (perhaps related to HW constraints)?

**Comment by jb55** [comment]
On Mon, Sep 18, 2023 at 05:06:15PM -0700, Daniel D’Aquino wrote:
>I did a quick test, but unfortunately I could not repro this issue yet. Here is what I tried:
>
>**iOS:** iOS 17.0 (iPhone 14 Pro) (Unable to test on a physical device at the moment)

yes it's most likely a physical device thing. simulator is just too
different. Is there any way for you to test iOS17 on a physical phone?
It should be availble..

**Comment by danieldaquino** [comment]
> Is there any way for you to test iOS17 on a physical phone?
> It should be availble..

Yes! It seems that the iOS 17 update is available for my iPhone. I will upgrade it as soon as possible to help me with testing.

My concern is having access to debugging or crash logs once I do see the crash on my iPhone. Xcode does not let me build and run Damus on my physical phone using my personal Apple developer account (I believe it is due to Damus having special [API entitlements](https://developer.apple.com/documentation/bundleresources/entitlements) that are not available to my free account, but haven’t looked extensively if there is a way I can workaround that).

**Comment by danieldaquino** [comment]
I got tooling to test this with, and I am actively investigating this now 👍

I believe I saw the issue happening for the first time a few minutes ago on my iPhone, will work to get more data.

**Comment by danieldaquino** [comment]
@jb55, @alltheseas, I have good news! I was able to root cause and fix (at least one of) the freezing issues.

I fixed the one that is described here: [https://damus.io/note162rt4fctxepnj9cdtr9a82k7jtw3e33hj742ejly3q84tkwsfars4k9glr](https://damus.io/note162rt4fctxepnj9cdtr9a82k7jtw3e33hj742ejly3q84tkwsfars4k9glr)

The patch, all investigation details, and testing reports can be found here: [https://groups.google.com/a/damus.io/g/patches/c/-NfhiWbMLD0](https://groups.google.com/a/damus.io/g/patches/c/-NfhiWbMLD0) (Sent over email)

I tried doing some random testing to check if I could see any other freezes/crashes, but did not find any other issues (yet). Please let me know if you see other issues with navigation, and the repro steps for them (if possible).

Thank you!

**Comment by danieldaquino** [comment]
Here is what I tried to do to check if there are any other nav crashes/freezes:

**iOS:** iOS 17.0.1 (iPhone 13 mini)
**Damus:** `cf7efb20a11033bc14d6aa947070327efb6de36f` (My patch)
**Special remarks:** Local build with local signature and no app entitlements
**Steps:**

1. Sign in with @jb55's npub (i.e. a busy account)
2. Scroll fast down the home view
3. Click on random profiles and notes to get to a very deep level of navigation (At least 10 levels deep), while requesting follower counts on each (to increase load on the app)
4. Scroll down fast
5. Quickly tap "back" buttons to go back to the root view on some, then "swipe back" on other profiles. Mix the two ways. 
6. Click on a few more notes/profiles

**Results:** I saw no crashes nor any freezes on my end

Hopefully there are no other crashes or freezes, but please let me know if you see one after my patch 😅

**Comment by jb55** [comment]
On Fri, Sep 22, 2023 at 06:54:11PM -0700, Daniel D’Aquino wrote:
>@jb55, @alltheseas, I have good news! I was able to root cause and fix (at least one of) the freezing issues.

amazing! seems to work. can't believe it was that simple 🤦

**Comment by alltheseas** [comment]
@danieldaquino going ham

🏋️‍♂️
