### ISSUE TITLE
Increase note ellipsis hit box so I have a 90% chance of success with the first tap

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1454]
_what happens_
I have to tap 3-4 times to open the note ellipsis menu

_why I think this happens_
Ellipsis hit box is tiny

![image](https://github.com/damus-io/damus/assets/64376233/b183b122-a1c5-4dda-94bb-03410a33516a)

**Comment by danieldaquino** [comment]
Created a patch the addresses this.

## New hit box size

For illustration purposes, here is a screenshot with the new hit box painted in red:

![Simulator Screenshot - iPhone 14 Pro - 2023-09-15 at 22 16 28](https://github.com/damus-io/damus/assets/24692108/531cc59e-3d4f-4ffc-9927-5b74d6fc81ca)

I was able to do so in a way that does not affect the layout and spacing of the other elements. Please note that if other elements (such as the user title) comes in front of a portion of the hit box, those other elements may have the priority for hit testing.

## Testing

**PASS**

**iOS:**
-  iOS 17.0 (iPhone 14 Pro simulator)
-  iOS 16.4 (iPhone 14 Pro simulator)
- _(I wanted to test on my physical iPhone device, but I could not run Damus on it because my Apple developer ID does not have access to certain extra app privileges that only paid accounts have, I believe)_

**Damus:** `fa3f83232a2207d3907a0fdb38b50b47ec48e24c`
**Steps:**
1. Scroll down and view several notes. Make sure their layout is not affected, and they all look normal
2. Tap on areas close to the ellipsis button (but not on it). Make sure that it triggers the menu
3. Tap on the very centre of the ellipsis button. Make sure that it triggers the menu
4. Start composing a new note. Click on a spot where an ellipsis button would be if we were not composing a note. Make sure that the ellipsis button is not clickable when there is an object in front of it (e.g. new note editor)

## Patch

I have submitted a patch via email. It can be viewed here: [https://groups.google.com/a/damus.io/g/patches/c/TvQDlvqviUk](https://groups.google.com/a/damus.io/g/patches/c/TvQDlvqviUk)

@jb55, @alltheseas, Please let me know if this size is good, or if you need any further changes. Thank you!

**Comment by alltheseas** [comment]
Thanks @danieldaquino 💪 

I suggest we push this fix, and have users test in production, the Damus way™️

**Comment by jb55** [comment]
On Fri, Sep 15, 2023 at 10:48:17PM -0700, Daniel D’Aquino wrote:
>Created a patch the addresses this.
>
>## New hit box size
>
>For illustration purposes, here is a screenshot with the new hit box painted in red:
>
>![Simulator Screenshot - iPhone 14 Pro - 2023-09-15 at 22 16 28](https://github.com/damus-io/damus/assets/24692108/531cc59e-3d4f-4ffc-9927-5b74d6fc81ca)

seems very large but maybe thats ok. will test.
