### ISSUE TITLE
Damus cannot parse NWC url's when the relay is url encoded.

### ISSUE THREAD

**Issue by benthecarman** [damus-io/damus#1536]
Per the [spec](https://github.com/nostr-protocol/nips/blob/master/47.md) it has the relay url url encoded in the nwc url.

`nostr+walletconnect:b889ff5b1513b641e2a139f661a661364979c5beee91842f8f0ef42ab558e9d4?relay=wss%3A%2F%2Frelay.damus.io&secret=71a8c14c1407c113601079c4302dab36460f0ccd0ad506f1f2dc73b5100e4f3c`

However for damus to be able to parse it you need to change it to
`nostr+walletconnect:b889ff5b1513b641e2a139f661a661364979c5beee91842f8f0ef42ab558e9d4?relay=wss://relay.damus.io&secret=71a8c14c1407c113601079c4302dab36460f0ccd0ad506f1f2dc73b5100e4f3c`

**Comment by danieldaquino** [comment]
@benthecarman, @alltheseas, I took a quick look at this, but I am seeing a slightly different issue. Both URLs given seem to fail, but for a different reason:

- Both URLs seem to fail on my end
- If I add `//` to the URL (after the schema), it works on my end

In more detail, here is what I tried:

### Experiment

**iOS:** 16.4 (iPhone 14 Pro)
**Damus:** 1.6 (17) `b18a0c57`
**Generic steps:**

1. Open Damus
2. Open "Wallet" settings
3. Click "Attach wallet"
4. Enter the test URL (In my case I use the paste feature)
5. Go back to "Attach wallet" and see if the app accepted the URL

**Results:**

| Test URL |  Result |
|---------|--------|
| `nostr+walletconnect:b889ff5b1513b641e2a139f661a661364979c5beee91842f8f0ef42ab558e9d4?relay=wss%3A%2F%2Frelay.damus.io&secret=71a8c14c1407c113601079c4302dab36460f0ccd0ad506f1f2dc73b5100e4f3c` | I get "Invalid Nostr wallet connection string" |
| `nostr+walletconnect:b889ff5b1513b641e2a139f661a661364979c5beee91842f8f0ef42ab558e9d4?relay=wss://relay.damus.io&secret=71a8c14c1407c113601079c4302dab36460f0ccd0ad506f1f2dc73b5100e4f3c` | I get "Invalid Nostr wallet connection string" | I get "Invalid Nostr wallet connection string" |
| `nostr+walletconnect://b889ff5b1513b641e2a139f661a661364979c5beee91842f8f0ef42ab558e9d4?relay=wss%3A%2F%2Frelay.damus.io&secret=71a8c14c1407c113601079c4302dab36460f0ccd0ad506f1f2dc73b5100e4f3c` | I am able to successfully connect, and the relay displayed on screen is `wss://relay.damus.io` (i.e. It seems to be decoding the URL encoded portion correctly) |

_(**Note:** You may need to scroll table horizontally to see all columns)_

---------

Now, when I looked at the code, I have a good idea of the root cause of the `//` issue. But I did not find any issues with URL encoding of the relay.

I would like to confirm whether we are looking at two different issues, or just one issue. @benthecarman, can you please share with us:

1. iOS and Damus version where you are seeing this issue
2. Whether the URL `nostr+walletconnect://b889ff5b1513b641e2a139f661a661364979c5beee91842f8f0ef42ab558e9d4?relay=wss%3A%2F%2Frelay.damus.io&secret=71a8c14c1407c113601079c4302dab36460f0ccd0ad506f1f2dc73b5100e4f3c` works on your end (i.e. whether it correctly parses the relay URL to `wss://relay.damus.io`)?

**Comment by benthecarman** [comment]
Hmm i can't reproduce anymore will close

**Comment by danieldaquino** [comment]
@benthecarman, thank you for confirming that you are no longer seeing an issue with URL encoding.

@alltheseas, I opened #1547 to continue investigation on the forward slashes issue and to fix it.
