### ISSUE TITLE
Detect no follow list profiles & prompt to create

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1621]
_what happens_
When I am creating a new profile, if I have a poor internet connection, I can become stuck without a follows list 

_what I suggest should happen_
Damus could auto-check follows list exists for a profile. If it does not exist, Damus can prompt "create a contact list?" on bootup

_implementation_
Nostrdb should store contact list locally. Therefore online or offline state should not affect the detection of presence of a contact list. 

![image](https://github.com/damus-io/damus/assets/64376233/aefcda7c-7a08-4bde-b262-2a31d30de9a2)

**Comment by jb55** [comment]
On Wed, Oct 18, 2023 at 06:56:50PM -0700, alltheseas wrote:
>Damus could auto-check follows list exists for a profile. If it does not exist, Damus can prompt "create a contact list?" on bootup

suggest:

1. Look in nostrdb first. This works offline and will happen automatically once we have a filter interface to nostrdb.

2. Only ask when you try to follow someone. This is probably more reliable than on startup, since we may not have received the contact list yet immediately on startup.

**Comment by alltheseas** [comment]
This is automated detect and suggest first aid

**Comment by alltheseas** [comment]
Duplicate of https://github.com/damus-io/damus/issues/2193
