### ISSUE TITLE
Space or punctuation or non alphanumeric characters breaks npub mention

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1721]
Bitcoin park

https://github.com/damus-io/damus/assets/64376233/3fa79259-bdaa-46b8-9175-1fb3d2cf6ef9

Also nostr.build https://damus.io/note18qwde6fwz0q7wyeh4qf5h9vush6t8j0p2tc9c8s56a5msgx8s39smy32ne

**Comment by alltheseas** [comment]
Possibly related to https://github.com/damus-io/damus/issues/1375 cc @danieldaquino

**Comment by alltheseas** [comment]
Added non-alphanumeric characters to scope

https://damus.io/note1zkja6n9mq6aqjqszx563ptwrkw8j88fcy8nal8t4t6ep3r6mz3uslklxfl

> if you have any semicolons or symbols in your username, you are rather impossible to find and tag on damus, unless we know your npub, which we'd have to find from nostr.band etc.

> this goes to The:Daniel and some others

**Comment by fishcharlie** [comment]
This is a tough one from a technical standpoint. As an example how do we differentiate between the user typing a space as like the next word in their note vs typing a space to further filter the search field?

Not saying we should emulate other clients. But from a UX and product standpoint it can give some good inspiration. So I tested this in both Ivory (https://tapbots.com/ivory/) & Bluesky (https://blueskyweb.xyz), and both behave the same way as Damus does currently.

I should also mention however. With #1620 the specific video posted in the OP should be improved, since it's now sorting by following.

Not saying we shouldn't do this. But it needs to be further flushed out before it's workable IMO. Unless someone has a very clear vision for how to achieve this in a clean way. I however don't have that vision right now.

**Comment by jb55** [comment]
On Sun, Jan 07, 2024 at 12:23:55PM -0800, Charlie Fish wrote:
>This is a tough one from a technical standpoint. As an example how do
>we differentiate between the user typing a space as like the next word
>in their note vs typing a space to further filter the search field?

Everything except a space should work imo, I think The:Daniel current
does not work.
