### ISSUE TITLE
Hell thread note crash

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1826]
> Every time I open this it crashes Damus. Never seen a note that does that. 

nostr:npub1xtscya34g58tk0z605fvr788k263gsu6cy9x0mhnm87echrgufzsevkk5s nostr:npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5 nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj

### related

https://github.com/damus-io/damus/issues/1489

**Comment by jb55** [comment]
On Mon, Dec 18, 2023 at 07:13:55AM -0800, alltheseas wrote:
>> Every time I open this it crashes Damus. Never seen a note that does that.
>
>nostr:npub1xtscya34g58tk0z605fvr788k263gsu6cy9x0mhnm87echrgufzsevkk5s
>nostr:npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5
>nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj

Let's fix this this week. Don't want people to be exploiting this and
crashing everyone.

**Comment by alltheseas** [comment]
Will you 
 @jb55 or should @danieldaquino take this

**Comment by alltheseas** [comment]
I submitted a crash report for this. I imagine others submitted as well. @danieldaquino to pick up

**Comment by danieldaquino** [comment]
I was able to reproduce it 3/3 times with this link: `nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj`

### Issue repro details

**Device:** iPhone 13 Mini (physical device)
**iOS:** 17.2
**Damus:** `a2cac142c077f3a91f3d719b400a4a09ff7761cf` (Current tip of master)
**Steps:**
1. Create a page with a link to `nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj`
2. Click on the link
3. Check if Damus will crash

**Repro rate:** 3/3 (100%)
**Notes:** Could not reproduce the issue on the iOS simulator. (0/3 repro rate)

### Other links

>nostr:npub1xtscya34g58tk0z605fvr788k263gsu6cy9x0mhnm87echrgufzsevkk5s nostr:npub1zafcms4xya5ap9zr7xxr0jlrtrattwlesytn2s42030lzu0dwlzqpd26k5 

@alltheseas, I am not sure why these npub links were included in the description. Are they causing crashes on your end as well? (They are working well for me)

**Comment by alltheseas** [comment]
@danieldaquino disregard npubs. Not sure how they ended up there

**Comment by danieldaquino** [comment]
### Update & notes

I have run the repro 10 times so far, looking at different things in the debugger. Here are some notes:
1. The issue is always an invalid memory access (`EXC_BAD_ACCESS`) (At least on all occasions where I took note of it)
2. The specific line where the invalid memory access happens varies (The stack trace is different each time I try it), but it is always happening around the NostrDB as far as I have observed
3. It seems to be triggered shortly after we try to load the dozens of profiles mentioned by the note

@jb55, my observations lead me to believe this might be some form of race condition related to the lifecycle of NostrDB transactions when loading several profiles at once.

I will do a deeper investigation on that.

**Comment by danieldaquino** [comment]
I am also seeing what appears to be a stack overflow.

About 6/10 appears to be a stack overflow
About 4/10 appears to be invalid memory access related to NostrDB transactions

**Comment by jb55** [comment]
On Mon, Dec 18, 2023 at 01:20:55PM -0800, Daniel D’Aquino wrote:
>I am also seeing what appears to be a stack overflow.
>
>About 6/10 appears to be a stack overflow
>About 4/10 appears to be invalid memory access related to NostrDB transactions

I wonder if it's related to the transaction inheritence commit I did
recently, if the first transaction is ever closed before the inherited
ones are, then there might be situation where data is being read from a
closed transcation...

If you log the deinit you should be able to see if the transaction is
closed while inherited ones are still active.

Might need to remove that "feature".

**Comment by danieldaquino** [comment]
> I wonder if it's related to the transaction inheritence commit I did recently, if the first transaction is ever closed before the inherited ones are, then there might be situation where data is being read from a closed transcation... If you log the deinit you should be able to see if the transaction is closed while inherited ones are still active. Might need to remove that "feature".

Interesting, I will test on an older Damus version (prior to that commit) to see what the behaviour is there.

**Comment by danieldaquino** [comment]
## Regression check

**Status:** Regression detected
**Device:** iPhone 13 Mini (physical device)
**iOS:** 17.2
**Damus:** 1.6.1 (30) (`2ece2eecd9f31669f7932c0f1b3f553d2daf3729`)
**Steps:**
1. Create a page with a link to nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj
2. Click on the link
3. Check if Damus will crash

**Observed behaviour:** Crashes almost immediately due to what appears to be a stack overflow (`EXC_BAD_ACCESS` on `_chkstk_darwin`, which appears to be a system function that checks if there is enough space in the stack). **I did not observe any memory errors on accessing NostrDB transactions**
**Repro rate:** 8/8

### Notes

It seems that we are looking at two issues. The stack overflow issue that affects older versions (1.6.1), and the apparent Ndb txn issues that seems to have been recently introduced.

**Comment by danieldaquino** [comment]
> If you log the deinit you should be able to see if the transaction is closed while inherited ones are still active. Might need to remove that "feature".

I will try this on the tip of master to help confirm if the `txn` issue is due to transaction inheritance changes

**Comment by danieldaquino** [comment]
## Experiment with TXNDEBUG=1 (tip of master)

**Summary:**
- In 2/10 iterations, the crash involved a bad `txn` access
    - In these cases, it appeared that the `txn_count` went from the `0 – 1` range to `1 – 2` or `1 – 3`.
    - @jb55, is it correct to say that Ndb should have a max of 1 transaction open at a time? That is the range I have observed during normal operation
- In 8/10 iterations, the crash involved a stack overflow

**Device:** iPhone 13 Mini (physical device)
**iOS:** 17.2
**Damus:** `a2cac142c077f3a91f3d719b400a4a09ff7761cf` (Current tip of `master`)
**Flags:** `TXNDEBUG=1`
**Steps:**

1. Create a page with a link to `nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj`
2. Click on the link
3. Check if Damus will crash
4. Observe logs and stack trace

**Detailed results:**
1. Stack overflow. `txn_count` roughly varies between 1 and 3
2. `EXC_BAD_ACCESS` when accessing `txn`. Logs indicate a transaction was opened right after quitting ingester and writer thread (when backgrounding/foregrounding the app)
```
**📙 DAMUS BACKGROUNDED**

**opening transaction 1**

**closing transaction 0**

**opening transaction 1**

**closing transaction 0**

**quitting ingester thread**

**quitting ingester thread**

**quitting ingester thread**

**quitting ingester thread**

**quitting writer thread**

**opening transaction 1**
```
3. Stack overflow. `txn_count` roughly varies between 0 and 1
4. Stack overflow. `txn_count` roughly varies between 0 and 2
5. `EXC_BAD_ACCESS` when accessing `txn` just as the app was backgrounded
```
**📙 DAMUS BACKGROUNDED**

**opening transaction 1**

**closing transaction 0**

**opening transaction 1**

**closing transaction 0**

**quitting ingester thread**

**quitting ingester thread**

**quitting ingester thread**

**quitting ingester thread**

**quitting writer thread**

**opening transaction 1**
```
6. Stack overflow. `txn_count` roughly varies between 1 and 2
7. Stack overflow. `txn_count` roughly varies between 0 and 1
8. Stack overflow. `txn_count` roughly varies between 0 and 1
9. Stack overflow. `txn_count` roughly varies between 0 and 1
10. Stack overflow. `txn_count` roughly varies between 0 and 1

### Next step

I will try to revert https://github.com/damus-io/damus/commit/da2bdad18d1ddc3f2bde40dcb16aca6677fd681c and retest the same thing. @jb55, please let me know if that's not the txn inheritance commit you mentioned earlier

**Comment by danieldaquino** [comment]
## Experiment with TXNDEBUG=1 (tip of master + `da2bdad` reverted)

**Summary:** In 10/10 iterations, the crash was caused due to stack overflow. `txn_count` never left the 0–1 range

**Device:** iPhone 13 Mini (physical device)
**iOS:** 17.2
**Damus:** `a2cac142c077f3a91f3d719b400a4a09ff7761cf` (Current tip of `master`) + https://github.com/damus-io/damus/commit/da2bdad18d1ddc3f2bde40dcb16aca6677fd681c reverted
**Flags:** `TXNDEBUG=1`
**Steps:**

1. Create a page with a link to `nostr:note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj`
2. Click on the link
3. Check if Damus will crash
4. Observe logs and stack trace

**Detailed results:**
- Stack overflow and `txn_count` roughly varying between 0 and 1 on all 10 iterations

### Next step

The revert seems to be effective in solving the `txn` related crashes. I will investigate the 2nd issue related to stack overflows

**Comment by danieldaquino** [comment]
The stack overflow seems to be caused by what looks like an infinite recursion happening around SwiftUI. Here is a backtrace I got from lldb during the crash:

```
(lldb) bt
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16cd57ff8)
  * frame #0: 0x00000001f493ba50 libsystem_pthread.dylib`___chkstk_darwin + 60
    frame #1: 0x000000018fa9e7b0 SwiftUI`___lldb_unnamed_symbol196643 + 120
    frame #2: 0x000000019004faec SwiftUI`___lldb_unnamed_symbol240203 + 84
    frame #3: 0x000000018fa9ff40 SwiftUI`___lldb_unnamed_symbol196656 + 184
    frame #4: 0x000000018fa9e9e8 SwiftUI`___lldb_unnamed_symbol196643 + 688
    frame #5: 0x000000019004faec SwiftUI`___lldb_unnamed_symbol240203 + 84
    frame #6: 0x000000018fa9ff40 SwiftUI`___lldb_unnamed_symbol196656 + 184
    frame #7: 0x000000018fa9e9e8 SwiftUI`___lldb_unnamed_symbol196643 + 688
    frame #8: 0x000000019004faec SwiftUI`___lldb_unnamed_symbol240203 + 84
    frame #9: 0x000000018fa9ff40 SwiftUI`___lldb_unnamed_symbol196656 + 184
    frame #10: 0x000000018fa9e9e8 SwiftUI`___lldb_unnamed_symbol196643 + 688
   (... omitted for brevity)
    frame #1525: 0x000000018fa9e9e8 SwiftUI`___lldb_unnamed_symbol196643 + 688
    frame #1526: 0x000000019004faec SwiftUI`___lldb_unnamed_symbol240203 + 84
    frame #1527: 0x000000018fa9ff40 SwiftUI`___lldb_unnamed_symbol196656 + 184
    frame #1528: 0x000000018fa9e9e8 SwiftUI`___lldb_unnamed_symbol196643 + 688
    frame #1529: 0x000000019004faec SwiftUI`___lldb_unnamed_symbol240203 + 84
    frame #1530: 0x000000018f78b038 SwiftUI`___lldb_unnamed_symbol173162 + 484
    frame #1531: 0x000000018f9bd0fc SwiftUI`___lldb_unnamed_symbol189225 + 552
    frame #1532: 0x000000018f05c8d4 SwiftUI`___lldb_unnamed_symbol116136 + 2064
    frame #1533: 0x000000018f05df84 SwiftUI`___lldb_unnamed_symbol116140 + 1464
    frame #1534: 0x000000018ec8b2dc SwiftUI`___lldb_unnamed_symbol91327 + 24
    frame #1535: 0x00000001b2b02864 AttributeGraph`AG::Graph::UpdateStack::update() + 512
    frame #1536: 0x00000001b2af9514 AttributeGraph`AG::Graph::update_attribute(AG::data::ptr<AG::Node>, unsigned int) + 424
    frame #1537: 0x00000001b2b03f68 AttributeGraph`AG::Subgraph::update(unsigned int) + 848
    frame #1538: 0x000000018fdb6a6c SwiftUI`___lldb_unnamed_symbol219188 + 384
    frame #1539: 0x000000018fdb7f68 SwiftUI`___lldb_unnamed_symbol219246 + 24
    frame #1540: 0x000000018f428af8 SwiftUI`___lldb_unnamed_symbol144889 + 28
    frame #1541: 0x000000018fea240c SwiftUI`___lldb_unnamed_symbol225339 + 108
    frame #1542: 0x000000018fea0924 SwiftUI`___lldb_unnamed_symbol225235 + 96
    frame #1543: 0x000000018f41fba4 SwiftUI`___lldb_unnamed_symbol144664 + 84
    frame #1544: 0x000000018fdb7f30 SwiftUI`___lldb_unnamed_symbol219245 + 200
    frame #1545: 0x000000018fdb7e1c SwiftUI`___lldb_unnamed_symbol219244 + 72
    frame #1546: 0x000000018f77b624 SwiftUI`___lldb_unnamed_symbol172191 + 28
    frame #1547: 0x000000018ed6ed80 SwiftUI`___lldb_unnamed_symbol100932 + 116
    frame #1548: 0x000000018ed6ecec SwiftUI`___lldb_unnamed_symbol100931 + 36
    frame #1549: 0x000000018ed6ee18 SwiftUI`___lldb_unnamed_symbol100933 + 60
    frame #1550: 0x000000018a94f83c CoreFoundation`__CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 36
    frame #1551: 0x000000018a94e244 CoreFoundation`__CFRunLoopDoObservers + 548
    frame #1552: 0x000000018a94d960 CoreFoundation`__CFRunLoopRun + 1028
    frame #1553: 0x000000018a94d478 CoreFoundation`CFRunLoopRunSpecific + 608
    frame #1554: 0x00000001cdece4f8 GraphicsServices`GSEventRunModal + 164
    frame #1555: 0x000000018cd7162c UIKitCore`-[UIApplication _run] + 888
    frame #1556: 0x000000018cd70c68 UIKitCore`UIApplicationMain + 340
    frame #1557: 0x000000018f7814b8 SwiftUI`___lldb_unnamed_symbol172573 + 176
    frame #1558: 0x000000018f7812fc SwiftUI`___lldb_unnamed_symbol172571 + 152
    frame #1559: 0x000000018f3f1e90 SwiftUI`___lldb_unnamed_symbol143436 + 128
    frame #1560: 0x0000000103768118 damus`static damusApp.$main(self=damus.damusApp) at <compiler-generated>:0
    frame #1561: 0x000000010376dd44 damus`main at damusApp.swift:11:8
    frame #1562: 0x00000001ad686dcc dyld`start + 2240
```

I will inspect the view logic.

**Comment by danieldaquino** [comment]
Forgot to post a follow-up update yesterday.

I believe we have the stack overflow is likely being caused by an AttributeGraph cycle on a SwiftUI view (Similar to the problem described [here](https://devcodef1.com/news/1018150/understanding-swiftui-s-mysterious-behavior))

I was able to narrow it down and I found part of the problematic code path.

Here is the problematic path so far:

`NoteContentView` -> `body` -> `.onAppear` -> `load()` -> `preload_event()` -> `plan.data.artifacts_model.state = .loaded(arts)`

I could confirm this by verifying that disabling any part of the code path mentioned above and rerunning tests causes the stack overflow to not occur.

On Wednesday I will continue narrowing this down. The cycle seems to be happening further downstream, on a subsequent rendering pass (after the note artifacts are loaded).

**Comment by jb55** [comment]
On Tue, Dec 19, 2023 at 12:16:38PM -0800, Daniel D’Aquino wrote:
>Here is the problematic path so far:
>
>`NoteContentView` -> `body` -> `.onAppear` -> `load()` -> `preload_event()` -> `plan.data.artifacts_model.state = .loaded(arts)`
>
>I could confirm this by verifying that disabling any part of the code path mentioned above and rerunning tests causes the stack overflow to not occur.
>
>On Wednesday I will continue narrowing this down. The cycle seems to be happening further downstream, on a subsequent rendering pass (after the note artifacts are loaded).

I want to move the block parsing to nostrdb, so that no preloading needs
to happen for note artifacts. This would probably fix this.

**Comment by danieldaquino** [comment]
> I want to move the block parsing to nostrdb, so that no preloading needs to happen for note artifacts. This would probably fix this.

I don't think block parsing/preloading is the issue. I noticed I could get the note artifacts object to be computed without issues. 

It seems to be related to what happens when we give SwiftUI those artifacts to render. Something there makes SwiftUI go haywire.

**Comment by jb55** [comment]
On Wed, Dec 20, 2023 at 12:44:45PM -0800, Daniel D’Aquino wrote:
>> I want to move the block parsing to nostrdb, so that no preloading
>> needs to happen for note artifacts. This would probably fix this.
>
>I don't think block parsing/preloading is the issue. I noticed I could
>get the note artifacts object to be computed without issues.
>
>It seems to be related to what happens when we give SwiftUI those
>artifacts to render. Something there makes SwiftUI go haywire.

hmm I see. weird.

**Comment by danieldaquino** [comment]
<img width="1671" alt="Screenshot 2023-12-20 at 13 03 05" src="https://github.com/damus-io/damus/assets/24692108/757f8d50-1e5c-424d-81f1-8288841a7034">

**I.** This is the time the `NoteContentView` runs `load()`, computes the artifacts and updates the artifacts model (A published/observed object, which triggers a re-render of the SwiftUI)
**II.** This is roughly where the infinite recursion begins. I noticed through stack traces that at that point most of  `SelectedEventView` is already re-rendered, so the point where the cursor is very likely one of its subviews
**III.** The call shown at the bottom of the stack trace is likely the one in `SelectableText.swift:113`. I believe that file is where the AttributeGraph cycle is occurring.

**Comment by danieldaquino** [comment]
I was able to "hack" a solution! I will improve my solution and post more details soon

**Comment by danieldaquino** [comment]
The issue is in the `CompatibleText` class.

It manipulates and saves `Text` views into variables. Although I do not know _exactly_ why doing this causes an infinite recursion in this case, SwiftUI view objects are meant to be created/managed by SwiftUI. Saving SwiftUI views into a variable is not supported as far as I know, and likely causes issues with the SwiftUI runtime.

This hack allowed that huge note to render correctly without crashes:
```
diff --git a/damus/Views/NoteContentView.swift b/damus/Views/NoteContentView.swift
index 237f5787..c5f7c40c 100644
--- a/damus/Views/NoteContentView.swift
+++ b/damus/Views/NoteContentView.swift
@@ -77,7 +77,7 @@ struct NoteContentView: View {
                 TruncatedText(text: content)
                     .font(eventviewsize_to_font(size, font_size: damus_state.settings.font_size))
             } else {
-                content.text
+                Text(content.attributed)
                     .font(eventviewsize_to_font(size, font_size: damus_state.settings.font_size))
             }
         }
```

I will work on a nicer fix

**Comment by danieldaquino** [comment]
> It manipulates and saves Text views into variables. Although I do not know exactly why doing this causes an infinite recursion in this case, SwiftUI view objects are meant to be created/managed by SwiftUI. Saving SwiftUI views into a variable is not supported as far as I know, and likely causes issues with the SwiftUI runtime.

While I am working on a fix, I encountered the same bug with a different implementation that does not store `Text` objects, which invalidates my hypothesis above.

It is still not common practice to store SwiftUI views in variables as far as know, but I now believe the root cause is coming from adding up many `Text` view objects together. Not sure how SwiftUI handles View addition, but if it just puts them all together into a single `Group`, it might be hitting SwiftUI's limits in terms of how many view objects can be placed under a single parent view.

I have a fix, but it is causing issues with rendering custom hashtag images. I will have to go back to the drawing board later. I will provide more updates later today or on Friday.

**Comment by jb55** [comment]
On Wed, Dec 20, 2023 at 03:14:57PM -0800, Daniel D’Aquino wrote:
>It is still not common practice to store SwiftUI views in variables as
>far as know, but I now believe the root cause is coming from adding up
>many `Text` view objects together. Not sure how SwiftUI handles View
>addition, but if it just puts them all together into a single `Group`,
>it might be hitting SwiftUI's limits in terms of how many view objects
>can be placed under a single parent view.
>
>I have a fix, but it is causing issues with rendering custom hashtag
>images. I will have to go back to the drawing board later. I will
>provide more updates later today or on Friday.

This is getting quite into the weeds. I wonder if there is a simpler
mechanism we can use to protect against these kinds of notes. Maybe just
a simple limit on blocks, like it will refuse to render if it's over
some number of blocks?

**Comment by danieldaquino** [comment]
> This is getting quite into the weeds. I wonder if there is a simpler mechanism we can use to protect against these kinds of notes. Maybe just a simple limit on blocks, like it will refuse to render if it's over some number of blocks?

Good point! I created such mechanism. This is how it looks like when the note is too large:

<img width="376" alt="Screenshot 2023-12-22 at 12 34 13" src="https://github.com/damus-io/damus/assets/24692108/f10e7ef4-b89d-48a8-b66d-5714623060dd">

However, I made a fix so that the problematic note we saw in this ticket can be rendered _(as well as other, even larger notes)_

The only notes that would display the error message would be extremely spammy.

Sent patches via email with all the details! https://groups.google.com/a/damus.io/g/patches/c/B512SnZJ1jA

@jb55, Please let me know if you have any questions or concerns. Thank you!

**Comment by alltheseas** [comment]
@danieldaquino does it fix
This note: note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj

**Comment by danieldaquino** [comment]
> @danieldaquino does it fix This note: note1ttfgneka3lt6yuutmr0uls5xd6z975fgdzpfkxwwf40dd38pjcqqvzvxaj

@alltheseas, yep!
