### ISSUE TITLE
Auto-strip location data from photos

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#1990]
## user story

As a privacy conscious Damus media user, I would like Damus to auto-remove any geolocation data from my photos, so that I don't compromise my or other's privacy. 

### acceptance criteria

1. Damus auto-removes iOS geolocation data from media

### commentary

current default image hosting service nostr.build auto-removes location metadata

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqs9exa6etj60shhp3mqpv6ckdh6a226axxfc5jtzxl0y9qxpp3exjspr9mhxue69uhhwetvvdhk6efwdehhxarj9emkjmn99uq3kamnwvaz7tmwdaehgu3wdaexzmn8v4cxjmrv9ejx2a30qyv8wue69uhk6mmwv9jzu6nzx56jucm0d5arsvpcxqq3qamnwvaz7tmwdaehgu3wwa5kuegqzmph5

**Comment by kernelkind** [comment]
By using `PHPickerViewController` instead of `UIImagePickerController` for the photo library, we get access to the 'options' button which gives the user access to toggling whether location data should be included in their media. Unfortunately, I don't think apple provides an API to programmatically control the defaults for this setting, so it is always defaulted to the 'true' value.

Photo gallery with `PHPickerViewController`:
<img width="405" alt="image" src="https://github.com/damus-io/damus/assets/8139906/19dedae6-6a79-4930-821e-071cb6d1e0fe">

Toggling 'Location' off:
<img width="405" alt="image" src="https://github.com/damus-io/damus/assets/8139906/d3786396-ed49-4156-a2c0-16cd8645e426">

Photo gallery after toggling 'Location' off:
<img width="405" alt="image" src="https://github.com/damus-io/damus/assets/8139906/745d0bda-2e0d-40b2-9734-43138bee17d2">

Is it acceptable to make this 'options' pane visible to the user, but not have the location data toggled to off?

**Comment by jb55** [comment]
On Wed, Feb 14, 2024 at 08:53:31AM -0800, kernelkind wrote:
>By using `PHPickerViewController` instead of `UIImagePickerController`
>for the photo library, we get access to the 'options' button which
>gives the user access to toggling whether location data should be
>included in their media. Unfortunately, I don't think apple provides an
>API to programmatically control the defaults for this setting, so it is
>always defaulted to the 'true' value.

I think providing the option is enough if we can't do it by default
programmatically

**Comment by kernelkind** [comment]
When the user captures media using the camera in app, I think the media should be saved to the camera roll and the user be prompted with the photo library with the captured media pre-selected. Then the user can select whether they want to include/not include location data the same way.

Otherwise, we would need to strip the location data from the media ourselves so it can be handed off to the uploading service without location data. And the user wouldn't be given the option of keeping the location data, although this might not be a big deal.

**Comment by alltheseas** [comment]
> Then the user can select whether they want to include/not include location data the same way.

Can the default option be set to do not share location data?

> Otherwise, we would need to strip the location data from the media ourselves so it can be handed off to the uploading service without location data. And the user wouldn't be given the option of keeping the location data, although this might not be a big deal.

I think auto stripping the location data is the preferred solution. 

I perceive the inconvenience of not having location data as significantly lesser than accidentally sharing private location information.

**Comment by kernelkind** [comment]
Ok, so it sounds like the way to proceed is:
1. For selecting media from the photo library, the user will be presented with `PHPickerViewController`, which will give them the option to include or not include location data. Regardless of this selection, Damus will strip location data after the user has made their media selection.
2. For using the in app camera, the user will capture their media, then it will be saved to the user's photo library. The user will then be presented with their photo library with the captured media pre-selected, and all described in 1 will be applicable.

**Comment by jb55** [comment]
On Thu, Feb 15, 2024 at 10:13:11AM -0800, kernelkind wrote:
>1. For selecting media from the photo library, the user will be
>presented with `PHPickerViewController`, which will give them the
>option to include or not include location data. Regardless of this
>selection, Damus will strip location data after the user has made their
>media selection.

Correct. This means location would be stripped at 3 spots: iOS, damus,
and nostr.build 😅
