### ISSUE TITLE
QR scan does nothing

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2032]
_what happens_ 

When I scan a QR profile generated by Damus or other clients, there is a high likelihood nothing happens after the QR code is recognized by way of the border outline animation.

Observed by at least three people on 1.7.

**Comment by jb55** [comment]
It takes me 2 tries usually. Not sure what's up

**Comment by danieldaquino** [comment]
## Update

I have a work in progress solution for this, which will resolve this issue, but still needs some refinement.

The root cause seems to be on how state is handled on `QRCodeView`:
1. Scanning is blocked on fetching a profile event from either NostrDB or from relays, and will fail if the profile event is not found
2. When Damus fails to fetch a profile, _it silently fails_ without displaying any visible error message. The view stays the same, as if it is still scanning

Furthermore, `QRCodeView` has some issues that make it harder to understand and troubleshoot, and might it less reliable:
- The state of the view is scattered in a couple of independent variables that might lead to state incoherence, and is error prone
- Some loose causal relationships between certain events that may not play out as expected.

So, I believe what is happening with the scanner is that it is trying to fetch a profile, but it can't find it right away due to bad connectivity or delays caused by one of N possible causes, and then the view just silently fails. 

As part of fixing this, I am:
1. Removing the dependency on finding the profile event in order to display actions to the user. Even if we can't load the full profile, we should be able to show something useful to the user, such as the option to follow that pubkey.
2. Opening a profile preview sheet instead of navigating to the full profile page, to allow for quick actions and save up bandwidth by not loading their timeline right away
3. Refactoring most of that view to make state management more simpler, and less error-prone
4. Improving error management and handling
5. Making the view truly reflect the internal state of the scanner to the user.

**Comment by danieldaquino** [comment]
Submitted a PR for this ticket! All details and notes can be found here: https://github.com/damus-io/damus/pull/2685

cc @jb55 @alltheseas
