### ISSUE TITLE
Issues with disconnecting relays [100,000 sats]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#2072]
Unclear if related to slash relays issues

Users shawn and karnage cannot remove relays. I am not sure how to troubleshoot @danieldaquino 

https://damus.io/nevent1qqsvx5pc0023njqqq78y9rf9xcsahsjg7lxvawl7ggmcyyp8wvjrmzqprpmhxue69uhhyetvv9ujumn0wd68yct5dyhxxmmdqyvhwumn8ghj7ur4wfshv6tyvyhxummnw3ezumrpdejqzxnhwden5te0wfjkccte9ehhyctwvajhq6tvdshxgetkqy2hwumn8ghj7mn0wd68ytndd9kx7afwd3hkc4ndht4

https://damus.io/nevent1qqsrhpw78jsq2rs00sqct6lrdxjd0g0ga3vthcuftsrylzjqwakz8pqpr9mhxue69uhhwetvvdhk6efwdehhxarj9emkjmn99uq32amnwvaz7tm9v3jkutnwdaehgu3wd3skueqpr3mhxue69uhkummnw3ezuumgv9mku7t9v9nk2u3wdejhgtcpzpmhxue69uhkummnw3ezuamfdejs9rgfx6

**Comment by alltheseas** [comment]
One more user https://damus.io/nevent1qqspvmj5qqsfyj4g725s4wzuamqgfn73qxq4qz3w7fp4m4kkdqanamcpr9mhxue69uhhyetvv9ujuumwdae8gtnnda3kjctv9uq3wamnwvaz7tmjv4kxz7fwdehhxarj9e3xzmny9uq3vamnwvaz7tm9v3jkutnwdaehgu3wd3skuep0qy2hwumn8ghj7un9d3shjtnyv9kh2uewd9hj74zt60a

npub127ekpmm3w2ttqfe9r4j3hhflx0uw89lw7457pyd9dc7zp03ld4dswn7dvk

**Comment by alltheseas** [comment]
![image](https://github.com/damus-io/damus/assets/64376233/48ab3d85-1ba0-4966-8866-90478ab9c8d6)

**Comment by alltheseas** [comment]
https://damus.io/nevent1qqs0dheknm7apjcjjsrsx74ec8czm4mf9alzdms6h3yedf9mgypngsspzemhxue69uhhyetvv9ujumn0wd68ytnzv9hxgqg5waehxw309aex2mrp0yhxummnw3ezucn8qyd8wumn8ghj7un9d3shjtn0wfskuem9wp5kcmpwv3jhvqghwaehxw309aex2mrp0yh8qmr9vfehgu3wvdhk68355j9

@jb55 @danieldaquino if relays are borked this is poor UX for all. Suggest bumping to highest priority 🙏

**Comment by karnagebitcoin** [comment]
I am in the same boat.

1. Unable to edit relays in damus
2. Deleted and reset all relays in Snort without forward slash
3. Deleted Damus entirely
4. Reinstalled Damus
5. Got back in, see the same old relays

Is Damus caching my profile and fetching old relay selection? It seems to be the case. Despite having new updated relays, i'm still seeing the old ones, and this prevents me from doing anything on Damus other than reading notes.

**Comment by karnagebitcoin** [comment]
Adding 100,000 sat bounty to fix this.

**Comment by karnagebitcoin** [comment]
This seems to have happened with the update to 1.7x So.. whatever code difference was introduced there is probably the culprit.

**Comment by karnagebitcoin** [comment]
Update: I am able to add new relays, but I cannot delete the old ones. I also cannot click on them. It's as if they are in the "disabled" state and I can't interact with them. Trying to add the same relay gives me duplicate relay error.

**Comment by shawnyeager** [comment]
Shawn, here. This does seem to correspond with the 1.7 release. I’m experiencing the same problems as @karnagebitcoin notes:

1. I’m unable to disconnect or delete relays. 
2. Relays with trailing slashes do not connect, but I can’t fix them in-app (see above).
3. No relay changes made in Primal, Snort, or metadata.nostr.com reflect in Damus.

**Comment by karnagebitcoin** [comment]
I was finally able to fix my relays but it was the weirdest experience that doesn't follow any logic. Here's what I did / happened:

1. I noticed none of my relays were clickable, so I wasn't even able to disconnect them. 
2. Then I added nos.lol and was able to finally publish because this relay was not on my list but I was now connected.
3. Then Will said I may be using npub to publish, so I logged out and made sure to log in with nsec again. 
4. Same issues persisted, but the app then crashed and logged me out entirely. 
5. Logged in with nsec again, now my relays were gone, all but one (nostr.band remained). 
6. I added other relays that were not in the list anymore. They worked and connected.
7. Then the first relay I added (nos.lol) somehow got the trailing slash back and was "deactivated" same as other old relays. 

That's it. Seems like the app crashing fixed the stuck relays. No idea how to replicate for you guys.

**Comment by alltheseas** [comment]
One more report https://damus.io/nevent1qqs9qday5knn83l70nz9fv9uzkq99wsats3wyalnacac7lyzgn942vgprfmhxue69uhhyetvv9ujumn0wd68yurvv438xtnrdaksz9mhwden5te0wfjkccte9e3h2unjv4h8gtnx095szynhwden5te0danxvcmgv95kutnsw43qzyrhwden5te0dehhxarj9emkjmn90243vp

**Comment by danieldaquino** [comment]
I was able to replicate this issue _(or at least part of the issue)_ locally based on the symptoms reported.

## Issue repro

**Device:** iPhone 15 simulator
**iOS:** 17.4
**Damus version:** 1.8 (1) `247f313b` (Current tip of the `master` branch)
**Steps:**
1. Delete all connected relays
2. Add `wss://relay.damus.io/` (with the trailing slash) to the relay list
3. Try removing this newly added relay.
4. Try to post.

**Results:**
3. Relay cannot be removed from the list. (Did not work 2/2 times tried)
4. Posting does not work (Did not work 2/2 times tried)

**Other data:** Saw interesting app logs during this test, such as this one:
```
["EVENT",{"sig":"77696398abb490d3d097cd91af6545dc2a6e9c497a8c659e962ebd588d6204c140185c8ba65b1b9448116e92c2bdd7384360c4c870a26ffe97f831548788973a","id":"eafdfae115d8f2eb082371eff5dab4e70ed5eff6719f7e8c759ac64e9e9e2232","pubkey":"056b5b5966f500defb3b790a14633e5ec4a0e8883ca29bc23d0030553edb084a","created_at":1710948510,"content":"{}","tags":[["p","3efdaebb1d8923ebd99c9e7ace3b4194ab45512e2be79c1b7d68d9243e0d2681"],["p","056b5b5966f500defb3b790a14633e5ec4a0e8883ca29bc23d0030553edb084a"],["p","b9ceaeeb4178a549e8b0570f348b2caa4bef8933fe3323d45e3875c01919a2c2"]],"kind":3}]
attempt #7 to flush event '' to wss://relay.damus.io/ after 170.859375 seconds
could not find relay when flushing: wss://relay.damus.io/
```

I will start investigating the root cause.

**Comment by alltheseas** [comment]
Official bug meme dropped

![image](https://github.com/damus-io/damus/assets/64376233/7e16f569-05f8-4019-bdfc-8d298db8e0b9)

**Comment by danieldaquino** [comment]
I have a draft of the fix that seems to resolve this problem!

However, I modified code in several places _(to prevent issues with trailing slashes in the future)_ so I should do more thorough testing before sending it over.

**Comment by jb55** [comment]
On Wed, Mar 20, 2024 at 12:27:07PM -0700, Daniel D’Aquino wrote:
>I have a draft of the fix that seems to resolve this problem!
>
>However, I modified code in several places _(to prevent issues with trailing slashes in the future)_ so I should do more thorough testing before sending it over.

Thanks daniel! This was affecting lots of people it seems.

**Comment by danieldaquino** [comment]
Performed more thorough testing and sent the patch to patches@damus.io. 

Code, discussion, and testing reports can all be found there (https://groups.google.com/a/damus.io/g/patches/c/GW34cPfIq2Y)

Please let me know if there are any concerns or questions!

Thank you!

**Comment by alltheseas** [comment]
Thank you @danieldaquino 

@jb55 can we hot fix update the AppStore with this change alone?

**Comment by danieldaquino** [comment]
> @jb55 can we hot fix update the AppStore with this change alone?

I wrote and tested my changes on top of 1.8, but I can backport the changes to 1.7 if needed
