### ISSUE TITLE
GIFs are not animated after upload

### ISSUE THREAD

**Issue by jb55** [damus-io/damus#2157]
Probably related to existing issues:

- #1917 
- #1501 

In my case, I saved an image, and it saved with no extension. I can confirm it was actually a gif and animated. Perhaps it's trying to detect the filetype from the extension and if there is none it saves as jpeg when stripping metadata? That's the only thing I can think of. (EDIT: it doesn't look like it matches extensions)

**Comment by jb55** [comment]
this was supposed to be fixed in:

- https://github.com/damus-io/damus/commit/1214f1839d78d2d96e7be32532e294570f9682d9

but it looks like this is still occurring @kernelkind 

Maybe we should not touch gifs ?

**Comment by danieldaquino** [comment]
I am planning to jump into this after #2158 (unless someone else fixes this first)

**Comment by danieldaquino** [comment]
I will look into this now

**Comment by danieldaquino** [comment]
Issue reproduced

**Device:** iPhone 15 simulator
**Damus version:** `ada99418f6fcdb1354bc5c1c3f3cc3b4db994ce6`
**iOS:** 17.4

**Comment by danieldaquino** [comment]
I have a partial fix that works for some cases.

However, it seems that for newly saved GIF images, it only works when I post the same GIF… twice… which is a bit bizarre. Investigating that

**Comment by danieldaquino** [comment]
Ok, I think I know what the root cause of that weird behaviour is. It seems that when the image from the picker can only be loaded as a `UIImage` (as opposed to a file URL), it ends up going through the `processImage(image: UIImage)` function to remove GPS data, and that function incidentally converts the image to JPG.

I am thinking of the best way to fix this.

**Comment by jb55** [comment]
On Fri, Apr 26, 2024 at 08:36:57PM GMT, Daniel D’Aquino wrote:
>Ok, I think I know what the root cause of that weird behaviour is. It seems that when the image from the picker can only be loaded as a `UIImage` (as opposed to a file URL), it ends up going through the `processImage(image: UIImage)` function to remove GPS data, and that function incidentally converts the image to JPG.
>
>I am thinking of the best way to fix this.

We don't need to worry about gps data on gifs. Just need to
upload it directly and skip processImage step for gifs.

**Comment by danieldaquino** [comment]
@jb55, following up on that standup conversation, it seems that most other apps implement their own picker, which I honestly think makes for a worse UX because the user needs to explicitly grant access to their whole photo library or to select specific pictures to show up on the picker.

**Comment by jb55** [comment]
On Mon, Apr 29, 2024 at 10:14:28AM GMT, Daniel D’Aquino wrote:
>@jb55, following up on that standup conversation, it seems that most other apps implement their own picker, which I honestly think makes for a worse UX because the user needs to explicitly grant access to their whole photo library or to select specific pictures to show up on the picker.

yes I hate when apps do that, it's horrible and annoying.

**Comment by danieldaquino** [comment]
> We don't need to worry about gps data on gifs. Just need to upload it directly and skip processImage step for gifs.

Out of an abundance of caution, I did more research as well as some experimentation using exiftool on a random gif file, and it really seems like there is no (standard) way to include location metadata to GIF images ([1](https://superuser.com/a/556320)) ([2](https://www.w3.org/Graphics/GIF/spec-gif89a.txt)).

I was able to inject some location metadata to a GIF file using `exiftool` ([3](https://exiftool.org)) but no other programs recognized that location data was added, so it seems that `exiftool` just "force-added" it in a "hacky" non-standard way.

I will look into two options: 
- Reverting that commit, or
- Add a condition that skips the image processing step altogether for GIF images (Since it is safe to do so)

**Comment by danieldaquino** [comment]
> Reverting that commit

I read commit 1214f1839d78d2d96e7be32532e294570f9682d9 and a few other commits around that time and I feel that simply reverting it might not be the best way, so I will study it and make new changes on top of the current state of things

**Comment by danieldaquino** [comment]
Fixed and tested!

Patch with testing report and other details was sent via email to patches@damus.io, and it can be visualized here: https://groups.google.com/a/damus.io/g/patches/c/Rq-ClRrdlys

@jb55, please let me know if you have any suggestions, questions, concerns, or if there is some testing you would like me to run before pushing this change. Thank you!
