### ISSUE TITLE
Can't play .mov in embed view in Damus [bug]

### ISSUE THREAD

**Issue by alltheseas** [damus-io/damus#808]
_What happened_
.mov uploaded to nostr.build does not allow me to play in embed view in Damus, although first frame/preview is detected and displayed

_What I think should happen_
I should be able to play .MOV format embedded in Damus, similar to YouTube embed playback. 

Example: 

https://damus.io/note16ajpx0xqs4pnn5ejaz94ald80yddp4zgg3rm764gr03zrycvrfks5ekuvw

Origin: Quiet Warrior https://damus.io/note1rnlzr9sq2p0h2kz75l26xqx432643d500wqlcptfzsj4w7fu3r6qm9ln83

**Comment by bryanmontz** [comment]
@alltheseas For both of the notes mentioned above, the content has been removed from nostr.build, so they are no longer useful for testing.

I just uploaded a new .mov file, and it seems to work in Damus 1.4.0 (1) for me.
![Simulator Screen Recording - iPhone 14 Pro - 2023-03-31 at 23 21 40](https://user-images.githubusercontent.com/445882/229265368-cfe83015-083c-465b-9a94-078e16918ded.gif)

Unless I'm missing something about what the issue is.
