### ISSUE TITLE
Implement Nostr Wallet Connect [feature request]

### ISSUE THREAD

**Issue by stackingsaunter** [damus-io/damus#881]
I'd like to propose a NIP47 integration https://github.com/nostr-protocol/nips/pull/406 to Damus and propose a flow how can it be integrated within current app design. Nostr Wallet Connect allows users to connect their external lightning wallets like Alby, to Nostr mobile clients. This allows for one-click zaps, without confirming payments in mobile wallets.

Unlike [current Amethyst implementation](https://guides.getalby.com/overall-guide/alby-lightning-account/connect-your-alby-lightning-account-to-other-apps/connect-to-mobile-apps/connect-to-amethyst), I think it's not ideal UX to lead users into this feature during the paying invoice flow. A good place to set this would be in **Settings -> Zap**, where users will be able to set it once and forget about it.

Upon turning the feature on, users could:
- scan a QR code of generated NWC URI on desktop
- use a deep link that would lead them to https://nwc.getalby.com/
- provide NWC details manually

<img width="974" alt="Screenshot 2023-04-06 at 13 32 57" src="https://user-images.githubusercontent.com/68239231/230364802-96786200-1f3b-4c9f-8349-ef73c49a989a.png">

Scanning the QR code or coming back to Damus from Alby NWC service, app fills fields with session data:

<img width="1073" alt="Screenshot 2023-04-06 at 13 38 48" src="https://user-images.githubusercontent.com/68239231/230365968-f19cabda-079b-4071-ada0-6abb40c0bf30.png">

---

[Link to Figma](https://www.figma.com/file/Z4s1K4oeFeMHxgsYWBbV1j/Damus-iOS-(NWC)?node-id=1005-24853&t=GXEzCOuWuZtbmp6i-0)

**Comment by alltheseas** [comment]
Thank you for adding this @stackingsaunter. It is on the Damus roadmap, and was not on GitHub. 

Related:
https://github.com/damus-io/damus/issues/627

**Comment by alltheseas** [comment]
1MM bounty added https://damus.io/note186hdaczn3h99mxecq34qz0qkujfxvr560m6q6976rgm2eexnug9szhddqz

**Comment by alltheseas** [comment]
https://github.com/getAlby/nips/blob/master/47.md

**Comment by alltheseas** [comment]
> https://github.com/getAlby/nips/blob/master/47.md

Confirming this is reference spec.

**Comment by alltheseas** [comment]
## user story
As a Damus user who uses zaps, I would like to minimize friction when sending zaps, so that I can outzap other nostriches.

### acceptance criteria 
1. User can opt-in NWC an external NWC compatible service in zap settings
1b. User is warned of danger of making zaps one tap:
" ⚡️⚠️warning: one tap zaps are incredibly easy to send. Zaps are irreversible. Are you sure you want one tap zaps?"
2. When user is connected to NWC, the NWC "service" URL is displayed in settings 
3. User toggle NWC off or on
4. User can swap one NWC service with another
5. There is a tooltip that lists NWC compatible services (for now: "Get Alby")
6. Damus displays visually sats balance of NWC connected wallet [design Q: where is balance displayed]
7. If user has a LNURL set up prior to NWC setup, user is prompted if they want to overwrite their prior LNURL with the NWC LNURL
8. If user has no LNURL when setting up NWC, NWC setup imports the corresponding NWC LNURL to the user's profile.

**Comment by alltheseas** [comment]
https://github.com/nostr-protocol/nips/blob/master/47.md

**Comment by alltheseas** [comment]
@stackingsaunter if you're happy with the NWC implementation can you kindly close this issue 🙏
