### ISSUE TITLE
Link to Note should be a preview/embed

### ISSUE THREAD

**Issue by bebopkid** [damus-io/damus#95]
When posting a link to another person's note it should embed or preview the note in reference

**Comment by olheadinternet** [comment]
i've been playing with super stacked links to notes. 

currently it opens up a "chat" that includes replies to linked notes, and if the note with linked notes is itself a reply it also includes that conversation. 

maybe instead of opening chat, notes with note links, could be opened in a "links" thread that only lists the notes that are linked.

if they link to notes, that themselves have links, one could click those notes and it would expand these into this same list. but not include any replies. If you want to highlight an interaction, one could link to both the note and the reply.

Notes with only one link could have a preview, if a note has 2 or more note links it shouldn't have a preview, maybe a prompt to open this proposed "links" page in it's place.

**Comment by bebopkid** [comment]
Addressed in a previous update
